---

# Enforce standard workflow for all pipelines
workflow:
  rules:
    # allow running schedule pipeline for any ref
    - if: $CI_PIPELINE_SOURCE == "schedule"
    # switch from branch pipelines to merge request pipelines when a merge request is created
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # run MR pipeline
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # dont run branch pipeline when MR is open
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # if no open MR, run branch pipeline
    - if: $CI_COMMIT_BRANCH

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  #- template: Security/Container-Scanning.gitlab-ci.yml

megalinter:
  stage: test
  image: sres.web.boeing.com:5000/oxsecurity/megalinter-documentation:v8.1.0
  variables:
    HTTPS_PROXY: http://www-proxy.web.boeing.com:31060
    HTTP_PROXY: http://www-proxy.web.boeing.com:31060
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    SPELL_LYCHEE_ARGUMENTS: --exclude '/-/raw/[^/]+/$' --exclude boeing\.com --timeout 60 
    ENABLE: SPELL,MARKDOWN
    DISABLE_LINTERS: REPOSITORY_TRUFFLEHOG,REPOSITORY_DEVSKIM,MARKDOWN_MARKDOWN_LINK_CHECK

  script:
    - "/bin/bash /entrypoint.sh"
  
# https://docs.gitlab.com/ee/user/project/pages/index.html#parallel-deployments  
pages:
  stage: deploy
  image: sres.web.boeing.com:5000/python:3.13
  variables:
    PAGES_PREFIX: "" # No prefix by default
  pages:
    path_prefix: "$PAGES_PREFIX" # Use whatever value is set in the variable
  script:
    - export ENV PIP_INDEX_URL="https://${API_KEY}@sres.web.boeing.com/artifactory/api/pypi/pypi-releases/simple"
    - python3 -m venv venv  # Create a virtual environment
    - source venv/bin/activate  # Activate the virtual environment
    - pip install --trusted-host sres.web.boeing.com --upgrade pip  # Upgrade pip to the latest version
    - pip install --trusted-host sres.web.boeing.com -r requirements.txt
    - mkdocs build --site-dir public --no-directory-urls

  environment:
    name: "BDA Software ${PAGES_PREFIX}"
    url: "${BDA_PAGES_URL}/${PAGES_PREFIX}" # To make this Static set via settings uncheck use unique domain.

  artifacts:
    paths:
      - public
    expire_in: 1 week

  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH # Run on default branch (with default PAGES_PREFIX)
      changes:
        - README.md
        - docs/**/*
        - mkdocs.yml
        - requirements.txt
        - .gitlab-ci.yml
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" # Conditionally change the prefix for Merge Requests
      changes:
        - README.md
        - docs/**/*
        - mkdocs.yml
        - requirements.txt
        - .gitlab-ci.yml
      variables:
        PAGES_PREFIX: 'mr-$CI_MERGE_REQUEST_IID' # Prefix with the mr-<iid>, for example `mr-123`
