site_name: BDA Software
site_description: BDA Software DevSecOps GitLab page
repo_url: https://git.web.boeing.com/bda-software/tools/bda-devsecops-standards
repo_name: tools/bda-devsecops-standards
edit_uri: edit/main/docs/
copyright: BDA Software
docs_dir: docs # This sets the documentation directory to the root
theme:
  name: material
  palette:
    primary: teal
  palette:
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue

    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
     
  features:
    - navigation.tabs
    - content.action.edit

  icon:
    repo: fontawesome/brands/gitlab 

# Plugins
plugins:
  - search
  - include-markdown
  # https://github.com/jdoiro3/mkdocs-multirepo-plugin
  # - multirepo:
  #     cleanup: true
  #     keep_docs_dir: true
  #     nav_repos:
  #       - name: kubernetes-docs
  #         import_url: https://github.com/kubernetes/website/?branch=main&edit_uri=/blob/main/
  #         imports: [
  #           /README.md
  #         ]
nav:
  - Home: index.md
  - Resources: resources.md
  - About: about.md
 
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:BDASoftware@exchange.boeing.com
    - icon: fontawesome/solid/comments 
      link: mattermost://mattermost.web.boeing.com/bda-devops/channels/town-square
    - icon: fontawesome/solid/industry
      link: https://bsf.web.boeing.com/
  repository:
    show_info: true
    edit_uri: edit/main/docs/  # This is not working
